### ISSUE TITLE
Do you have any representatives that actually distribute apps?

### ISSUE THREAD

**Issue by mikehearn** [cabforum/code-signing#14]
Today DigiCert notified me that the code signing requirements are changing yet again, this time in a way that will require extra work for all app developers that use non-Store MSIX packaging pipelines with EV certs (the removal of the SAN component of the EV X.500 name). Windows uses a hash of the X.500 name to identify publishers, so any change in the naming conventions requires a [complicated workaround](https://learn.microsoft.com/en-us/windows/msix/package/persistent-identity) to ensure continuity of updates. This change was announced on 27th Oct and will happen in December so for anyone who gets their EV cert from DigiCert and renews after this time, they will have to understand this, learn how to work around it, integrate the fix into their packaging/release pipeline etc etc. All highly likely to cause breakages. Before, this was only required if the org changed name or moved its HQ.

As far as I can tell this change yields strongly negative value for app devs and no value to certificate consumers (Windows), it's just some sort of deprecation/churn. 

This is coming on the back of the now-delayed attempt to phase out the use of non-HSM protected keys, even for non EV certs.

Compare this to:

1. Apple. No HSM requirements. No tying of publisher IDs to arbitrary things like street addresses of HQ. Instead they maintain a DB of "team IDs" which are stable across time. Individuals can get certs with nothing more than a credit card.
2. SSL certs. No HSM requirements. Automatically issuable. Tied to relatively stable IDs like domain names.

The Windows code signing situation has clearly inferior usability to both of these, with apparently little interest in closing the gap?

I'm wondering if the CA/B forum has any representatives of app signers involved in these decisions, or whether there'd be interest in having some? I'm actually a tooling developer as well as an app dev, but maybe that's close enough. I'm concerned that the meeting notes imply that only CAs and one person from Microsoft turns up. Although in theory any of these parties could act as developer advocates and lobby on behalf of 'subscribers' (developers?), it's unclear from the outside to what extent that's really happening. Windows code signing requirements seem to be on a one-way ratchet of escalating measures and sometimes (like this time) hard to explain churn. If Apple - which has a good security reputation - can get away with their current ID verification measures, why can't Windows?

**Comment by mikehearn** [comment]
OK, thanks for the clarification. With respect to the other questions, is there interest in having some people distributing apps / making code signed packages in the working group, as the other questions around usability still stand.

**Comment by CBonnell** [comment]
We welcome participation by Interested Parties. You can find more information here: https://cabforum.org/interested-parties/.
